apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: backend
    spec:
      containers:
      - name: interceptor-frontend
        image: kudddy/frontendcube:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
            - name: BACKENDHOST
              value: http://backend-service:3000/api
        ports:
        - containerPort: 8080